[tool.poetry]
name = "onderwijs-analist-bot"
version = "0.1.0"
description = ""
authors = ["Job Visser <job.visser@leaseplan.com>"]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
